[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dissmodel-sysdyn"
version = "0.1.0"
description = "System dynamics models for DisSModel"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Sérgio Souza Costa", email = "sergio.costa@ufma.br" },
    { name = "Mateus Dutra Vale" },
    { name = "Nerval de Jesus Santos Junior" },
]
requires-python = ">=3.10"
dependencies = [
    "dissmodel>=0.5.0",
]

[project.optional-dependencies]
examples = [
    "streamlit",
]
dev = [
    "pytest",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["dissmodel_sysdyn", "dissmodel_sysdyn.models"]

[project.urls]
Homepage = "https://github.com/DisSModel/dissmodel-sysdyn"

[tool.pytest.ini_options]
testpaths = ["tests"]
